/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 014ad347eb44c1288082bb83614e923f)
interface __BaseEnv_Env {
	TOKEN_KV: KVNamespace;
	PUBLIC_BASE_URL: "";
	OAUTH_SCOPE: "tasks:read tasks:write";
	TOKEN_EXPIRY_REMIND_DAYS: "14";
	BOT_WEBHOOK_AUTH_STYLE: "both";
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	TOKEN_ENCRYPTION_KEY: string;
	ADMIN_KEY: string;
	BOT_WEBHOOK_URL: string;
	BOT_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_BASE_URL" | "OAUTH_SCOPE" | "TOKEN_EXPIRY_REMIND_DAYS" | "BOT_WEBHOOK_AUTH_STYLE" | "CLIENT_ID" | "CLIENT_SECRET" | "TOKEN_ENCRYPTION_KEY" | "ADMIN_KEY" | "BOT_WEBHOOK_URL" | "BOT_WEBHOOK_SECRET">> {}
}
